---
- name: Set ParallelDownloads to 5
  ansible.builtin.lineinfile:
    dest: /etc/pacman.conf
    regexp: "^#ParallelDownloads.*"
    line: "ParallelDownloads = 5"
    backup: true

- name: Enable Color
  ansible.builtin.lineinfile:
    dest: /etc/pacman.conf
    regexp: "^#Color.*"
    line: "Color"

- name: Enable multilib
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '^#\[multilib\]\n#Include.*'
    replace: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: Install AUR helper
  ansible.builtin.shell:
    cmd: |
      cd /tmp || exit 1
      git clone https://aur.archlinux.org/{{ aur_helper }}.git
      cd {{ aur_helper }}
      makepkg -si --noconfirm
    creates: /usr/bin/{{ aur_helper }}

# - name: Update System
#   community.general.pacman:
#     update_cache: true
#     upgrade: true
#     state: latest
