---
- name: Touchpad Configuration (X11)
  ansible.builtin.copy:
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
    content: |
      Section "InputClass"
        Identifier "touchpad"
        Driver "libinput"
        MatchIsTouchpad "on"
        Option "NaturalScrolling" "true"
        Option "Tapping" "true"
        Option "TappingButtonMap" "lrm"
      EndSection
    mode: "0644"
  when: ansible_form_factor == "Notebook"

- name: Mouse Configuration (X11)
  ansible.builtin.copy:
    dest: /etc/X11/xorg.conf.d/50-mouse-acceleration.conf
    content: |
      Section "InputClass"
        Identifier "My Mouse"
        Driver "libinput"
        MatchIsPointer "yes"
        Option "AccelProfile" "flat"
        Option "AccelSpeed" "0"
      EndSection
    mode: "0644"

- name: Intel Graphics Configuration (X11)
  ansible.builtin.copy:
    dest: /etc/X11/xorg.conf.d/20-intel.conf
    content: |
      Section "Device"
        Identifier "Intel Graphics"
        Driver "modesetting"
        Option "DRI" "3"
        Option "TearFree" "false"
        Option "TripleBuffer" "false"
        Option "SwapbuffersWait" "false"
      EndSection
    mode: "0644"
  when: "'GenuineIntel' in ansible_facts['processor']"

- name: Setup zshenv file
  ansible.builtin.lineinfile:
    path: /etc/zsh/zshenv
    line: 'export ZDOTDIR="$HOME"/.config/zsh'
    create: true
    mode: "0644"
