---
- name: Enable UFW Firewall
  community.general.ufw:
    state: enabled

- name: Set UFW to deny all incoming by default
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Set UFW to allow all outgoing by default
  community.general.ufw:
    direction: outgoing
    policy: allow
  notify: Reload UFW Firewall

- name: Limit SSH access to prevent brute force attacks
  community.general.ufw:
    rule: limit
    port: 22
    proto: tcp
  notify: Reload UFW Firewall

- name: Networking Kernel Parameters
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-network.conf
    state: present
  with_items:
    - { key: net.ipv4.ip_forward, value: 0 }
    - { key: net.ipv6.conf.all.forwarding, value: 0 }
    - { key: net.ipv4.tcp_syncookies, value: 1 }
    - { key: net.ipv4.conf.all.accept_redirects, value: 0 }
    - { key: net.ipv4.conf.default.accept_redirects, value: 0 }
    - { key: net.ipv4.conf.all.secure_redirects, value: 0 }
    - { key: net.ipv4.conf.default.secure_redirects, value: 0 }
    - { key: net.ipv6.conf.all.accept_redirects, value: 0 }
    - { key: net.ipv6.conf.default.accept_redirects, value: 0 }
    - { key: net.ipv4.conf.all.send_redirects, value: 0 }
    - { key: net.ipv4.conf.default.send_redirects, value: 0 }
  notify: Reload sysctl
