---
- name: Setup TTY
  ansible.builtin.copy:
    content: |
      KEYMAP=us
      FONT=ter-218b
    dest: /etc/vconsole.conf
    mode: "0644"

- name: Install Basic Packages
  ansible.builtin.package:
    name: "{{ system.basic_packages }}"
    state: present

- name: Install AUR helper
  ansible.builtin.shell:
    cmd: |
      cd /tmp || exit 1
      git clone https://aur.archlinux.org/{{ aur_helper }}.git
      cd {{ aur_helper }}
      makepkg -si --noconfirm
    creates: /usr/bin/{{ aur_helper }}
