---
- name: Setup TTY
  ansible.builtin.copy:
    content: |
      KEYMAP=us
      FONT=ter-v22b
      XKBLAYOUT=us
      XKBOPTIONS=caps:escape
    dest: /etc/vconsole.conf
    mode: "0644"

- name: Install Basic Packages
  ansible.builtin.package:
    name: "{{ system.basic_packages }}"
    state: present
