---
- name: Enable UFW Firewall
  community.general.ufw:
    state: enabled

- name: Set UFW to deny all incoming by default
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Set UFW to allow all outgoing by default
  community.general.ufw:
    direction: outgoing
    policy: allow
  notify: Reload UFW Firewall

- name: Limit SSH access to prevent brute force attacks
  community.general.ufw:
    rule: limit
    port: 22
    proto: tcp
  notify: Reload UFW Firewall
