[default_session]
startup_command = "ls"

[[session]]
name = "dwm"
path = "~/.config/suckless/dwm"
startup_command = "nvim config.h"

[[session]]
name = "shellrc"
path = "~/.config/shellrc"
startup_command = "nvim"

[[session]]
name = "testrc"
path = "~/testenv/rC"

[[session]]
name = "nvim"
path = "~/.config/nvim"
startup_command = "nvim"

[[session]]
name = "Notes"
path = "~/Documents/Notes"
startup_command = "nvim"

[[session]]
name = "starship"
startup_command = "nvim ~/.config/starship.toml"

[[session]]
name = "alacritty"
path = "~/.config/alacritty"
startup_command = "nvim alacritty.toml"

[[session]]
name = "ghostty"
path = "~/.config/ghostty"
startup_command = "nvim config"

[[session]]
name = "wezterm"
path = "~/.config/wezterm"
startup_command = "nvim wezterm.lua"

[[session]]
name = "sesh"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "tmux"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "downloads"
path = "~/Downloads"

[[session]]
name = "home"
path = "~"

[[session]]
name = "music"
path = "~/Music"
startup_command = "tmux neww -d -n \"spotify\" sptd && asong"
