---
- name: Update System
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Reload UFW Firewall
  community.general.ufw:
    state: reloaded

- name: Reload sysctl
  ansible.builtin.command:
    cmd: sysctl --system
