general {
  immediate_render = true
  hide_cursor = true
  screencopy_mode = 1
}

background {
  monitor =
  path = screenshot
  # path = $HOME/Pictures/Wallpapers/My Wallpapers/exoMountain.jpg
  blur_passes = 4
  blur_size = 4
}

label {
  monitor =
  text = $TIME
  color = rgba(242, 243, 244, 0.75)
  font_size = 93
  font_family = SF Pro Display Bold
  position = 0, 310
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:43200000] date +"%A, %B %d"
  color = rgba(242, 243, 244, 0.75)
  font_size = 20
  font_family = SF Pro Display
  position = 0, 405
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 200, 50

  outline_thickness = 0

  dots_size = 0.25
  dots_spacing = 0.30
  dots_center = true
  dots_rounding = -1

  inner_color = rgba(00000000)      # fully transparent
  outline_color = rgba(00000000)    # fully transparent

  font_size = 20
  font_color = rgba(FFFFFFAA)
  font_family = DankMono Nerd Font Italic

  fade_on_empty = false              # key setting
  hide_input = false                # allow dots to appear

  placeholder_text = Enter Password or die

  check_color = rgba(122,162,247,1.0)
  fail_color = rgba(247,118,142,1.0)
  capslock_color = rgba(224,175,104,1.0)

  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>

  position = -10, -300
  halign = center
  valign = center
}
