---
- name: Include DWM
  ansible.builtin.include_tasks: dwm.yml
  when: window_manager == 'dwm'

- name: Include Hyprland
  ansible.builtin.include_tasks: hyprland.yml
  when: window_manager == 'hyprland'

- name: Import User Setup
  ansible.builtin.import_tasks: user.yml
