#!/bin/sh

# Change directory aliases
alias cd.='cd .'
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'

# Replaced ls with eza
alias l=ls
alias la='ls -a'
alias lla='ll -a'
alias ll='ls -l --git --git-repos --header'
alias ls='eza --time-style=long-iso --icons --hyperlink --group-directories-first'

# Avoid Mistakes
alias cp='cp -Riv'
alias mv='mv -iv'
alias suod='sudo'

# Misc:
alias cat='bat' #alias cat='batcat' # For Debian and Debian based distros
alias phpr='xdg-open http://localhost:8000 && php -S localhost:8000 -t .'
alias ccat='/usr/bin/cat' # Normal Cat Command
alias cb='xclip -selection clipboard'
alias cls='clear'
alias grep='rg --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'
alias ip='ip --color=auto'
alias nf='neofetch'
alias nff='fastfetch'
alias quit='exit'
alias vi='vim'
alias upfor='echo -ne booted at:  && uptime --since && echo -ne "(running) " && uptime --pretty'
# for dwm quick compile
alias smci="sudo make clean install && yes | rm config.h && rm *.o && rm *.orig"
alias wget='wget --hsts-file="$XDG_DATA_HOME/wget-hsts"'

# From github.com/christitustech/mybash

# alias to show the date
alias da='date "+%Y-%m-%d %A %T %Z"'

# pacman
[[ -x /bin/pacman ]] && alias pacman='sudo pacman'
# Alias's to modified commands
[[ -x /bin/trash ]] && alias rm='trash -v'
alias mkdir='mkdir -p'
alias rd='rm -r'
alias less='less -R'
#alias apt-get='sudo apt-get'
#apt='sudo apt'
alias multitail='multitail --no-repeat -c'
alias freshclam='sudo freshclam'
[[ -x /bin/nvim ]] && alias sv='sudo --edit'
[[ -x /bin/nvim ]] && alias vim='nvim'
[[ -x /bin/nvim ]] && alias v='nvim'
[[ -x /bin/nemo ]] && alias nemo='setsid -f nemo $1 > /dev/null 2<&1'
[[ -x /bin/thunar ]] && alias thunar='setsid -f thunar $1 > /dev/null 2<&1'
[[ -x /bin/pcmanfm ]] && alias pcmanfm='setsid -f pcmanfm $1 > /dev/null 2<&1'
alias dots='/usr/bin/git --git-dir=$HOME/.config/.dotfiles/ --work-tree=$HOME'
