#!/bin/sh

export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'

fzf_history() {
    # Expand aliases and execute fzf
    eval "$(HISTTIMEFORMAT= history | sed 's/^ *[0-9]\+ *//g' | awk '!x[$0]++' | fzf --height=40% --reverse)"
}

extract_archive() {
    local archive
    archive=$(find . -type f -name '*.zip' -o -name '*.tar' -o -name '*.tar.gz' | fzf) && tar -xf "$archive"
}

psong() {
    local song
    song=$(find ~/Music -type f \( -name '*.mp3' -o -name '*.flac' -o -name '*.aac' -o -name '*.wav' \) | fzf) && setsid -f mpv "$song" > /dev/null 2<&1
}

loca() {
    locate "$1" | fzf | xargs -o nvim
}
