#!/bin/sh

export FZF_DEFAULT_OPTS='--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9 --color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9 --color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6 --color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4'

fzf_history() {
    # Expand aliases and execute fzf
    eval "$(HISTTIMEFORMAT= history | sed 's/^ *[0-9]\+ *//g' | awk '!x[$0]++' | fzf --height=40% --reverse)"
}

extract_archive() {
    local archive
    archive=$(find . -type f -name '*.zip' -o -name '*.tar' -o -name '*.tar.gz' | fzf) && tar -xf "$archive"
}

pvlc() {
    local song
    song=$(find ~/Music -type f \( -name '*.mp3' -o -name '*.flac' -o -name '*.aac' -o -name '*.wav' \) | fzf) && setsid -f vlc "$song" > /dev/null 2<&1
}
jp(){
    codeon=$HOME/1hundred/Dev/CodeOn
    selected_location=$(echo -e "wallpaper\nzsh\nshellrc\nskless\nsless\nkitty\nconf\ncode\ncoshell\ncocss\ndl\nbash\ndeploy\ndcmp\ndocker" | fzf --height=40% --reverse)
            case $selected_location in
				zsh) cd ~/.config/zsh ;;
                wallpaper) cd ~/Pictures/Wallpapers ;;
				shellrc) cd ~/.config/shellrc ;;
                skless) cd ~/.config/sucklessog/.suckless/ ;;
                sless) cd $HOME/.config/suckless ;;
                kitty) cd $HOME/.config/kitty ;;
                conf) cd ~/.config/ ;;
                code) cd $codeon ;;
                coshell) cd $codeon/shell ;;
                cocss) cd $codeon/css ;;
                dl) cd ~/Downloads/ ;;
                bash) cd $HOME/.bash/ ;;
                deploy) cd $HOME/1hundred/Dev/deploy/ ;;
                dcmp) cd $HOME/1hundred/Dev/deploy/docker/compose ;;
                docker) cd $HOME/1hundred/Dev/deploy/docker ;;
                *) echo "Invalid option" ;;
            esac
}


loca() {
  locate "$1" | fzf | xargs -o nvim
}
