#!/bin/zsh

# vi mode
bindkey -v
bindkey "^H" backward-kill-word
bindkey "^?" backward-delete-char
export KEYTIMEOUT=1
autoload edit-command-line; zle -N edit-command-line

# Use vim keys in tab complete menu:
# bindkey -M menuselect 'h' vi-backward-char
# bindkey -M menuselect 'k' vi-up-line-or-history
# bindkey -M menuselect 'l' vi-forward-char
# bindkey -M menuselect 'j' vi-down-line-or-history
# bindkey -v '^?' backward-delete-char

# Change cursor shape for different vi modes.
function zle-keymap-select {
    if [[ ${KEYMAP} == vicmd ]] ||
    [[ $1 = 'block' ]]; then
        echo -ne '\e[1 q'
    elif [[ ${KEYMAP} == main ]] ||
    [[ ${KEYMAP} == viins ]] ||
    [[ ${KEYMAP} = '' ]] ||
    [[ $1 = 'beam' ]]; then
        echo -ne '\e[6 q' # Changed to '\e[6 q' for a static bar cursor
    fi
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    echo -ne "\e[6 q" # Changed to '\e[6 q' for a static bar cursor
}
zle -N zle-line-init
echo -ne '\e[6 q' # Changed to '\e[6 q' for a static bar cursor on startup
preexec() { echo -ne '\e[6 q' ;} # Changed to '\e[6 q' to ensure a static bar cursor for each new prompt.
