#!/bin/sh

# Function to check if a module is loaded
is_module_loaded() {
    lsmod | grep -q "$1"
}

# Function to load a module if not already loaded
load_module() {
    if ! is_module_loaded "$1"; then
        sudo modprobe "$1"
    fi
}

# Function to unload a module if loaded
unload_module() {
    if is_module_loaded "$1"; then
        sudo rmmod "$1"
    fi
}

# Function to enable NVIDIA GPU for host usage
nhost() {
    # Run nvidia-enable
    sudo virsh nodedev-reattach pci_0000_01_00_0 && sudo virsh nodedev-reattach pci_0000_01_00_1 &&
    echo "GPU reattached (now host ready)" &&
    sudo rmmod vfio_pci vfio_pci_core vfio_iommu_type1 &&
    echo "VFIO drivers removed" &&
    sudo modprobe -i nvidia_modeset nvidia_uvm nvidia &&
    echo "NVIDIA drivers added" &&
    echo "COMPLETED! (confirm success with nvidia-query, and active-gpu-prime)" &&
    sudo rc-service nvidia-persistenced start
}

# Function to disable NVIDIA GPU and enable VFIO for virtualization
nvfio() {
    # Run nvidia-disable
    sudo rc-service nvidia-persistenced stop && sleep 1 &&

    # unload nvidia drivers
    sudo rmmod nvidia_drm nvidia_uvm
    unload_module nvidia_modeset
    unload_module nvidia

    # Load VFIO modules
    load_module vfio_pci
    load_module vfio_pci_core
    load_module vfio_iommu_type1

    echo "NVIDIA drivers removed" &&
    sudo modprobe -i vfio_pci vfio_pci_core vfio_iommu_type1 &&
    echo "VFIO drivers added" &&
    sudo virsh nodedev-detach pci_0000_01_00_1 &&
    sudo virsh nodedev-detach pci_0000_01_00_0 &&
    echo "GPU detached (now vfio ready)" &&
    echo "COMPLETED! (confirm success with nvidia-query and active-gpu)"
}

nfree(){
    unload_module nvidia
    unload_module nvidia_modeset
}

# Function to display GPU information
nstatus() {
    echo "NVIDIA Dedicated Graphics" | grep "NVIDIA" &&
    lspci -nnk | grep "NVIDIA Corporation GA107M" -A 2 | grep "Kernel driver in use" &&
    echo "Intel Integrated Graphics" | grep "Intel" &&
    lspci -nnk | grep "Intel.*Integrated Graphics Controller" -A 3 | grep "Kernel driver in use" &&
    echo "Confirm which GPU libraries are in use with (active-gpu and active-gpu-prime)" &&
    echo "Enable and disable the dedicated NVIDIA GPU with nvidia-host and nvidia-vfio"
}
