live_config_reload = true
working_directory = "None"

# Themes --
#import = [ "~/.config/alacritty/dracula.toml" ]
import = [ "~/.config/alacritty/catppuccin_macchiato.toml" ]

[window]
opacity = 0.6
padding.x = 10
padding.y = 10

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-kitty"

[font.normal]
family = "BlexMono Nerd Font"
style = "Medium"
