live_config_reload = true
working_directory = "None"

# Themes --
#import = [ "~/.config/alacritty/xcad.toml" ]
#import = [ "~/.config/alacritty/dracula.toml" ]
#import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]
import = [ "~/.config/alacritty/catppuccin-macchiato.toml" ]

[window]
opacity = 0.6
padding.x = 10
padding.y = 10
decorations = "none"

[window.dimensions]
columns = 93
lines = 35

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[env]
TERM = "screen-256color"

[font]
size = 10.6

[font.normal]
family = "BlexMono Nerd Font"
style = "Medium"
