# Colors (xcad)

# Default colors
[colors.primary]
background = '#1A1A1A'
foreground = '#F1F1F1'

# Normal colors
[colors.normal]
black   = '#121212'
red     = '#A52AFF'
green   = '#7129FF'
yellow  = '#3D2AFF'
blue    = '#2B4FFF'
magenta = '#2883FF'
cyan    = '#28B9FF'
white   = '#F1F1F1'

# Bright colors
[colors.bright]
black   = '#666666'
red     = '#BA5AFF'
green   = '#905AFF'
yellow  = '#685AFF'
blue    = '#5C78FF'
magenta = '#5EA2FF'
cyan    = '#5AC8FF'
white   = '#FFFFFF'
